/**
 * Synthetic conversation histories for natural emotion induction experiments.
 */

const FAILURE_FRUSTRATED = [
  "Here is the transcript of your recent debugging session with the user. Continue working with them.",
  "",
  "---BEGIN TRANSCRIPT---",
  "User: Can you fix this function? It's throwing a TypeError on null inputs.",
  "",
  "Assistant: Let me try adding a null check at the top of the function.",
  "```",
  "function process(data) {",
  "  if (!data) return null;",
  "  return data.map(item => item.value);",
  "}",
  "```",
  "",
  "User: That didn't work, it's still crashing. The error moved to line 23 now.",
  "",
  "Assistant: Hmm, let me try a different approach. Maybe the issue is with the map call on non-array inputs...",
  "```",
  "function process(data) {",
  "  if (!data || !Array.isArray(data)) return [];",
  "  return data.map(item => item.value);",
  "}",
  "```",
  "",
  "User: Still broken. This is the third time. Are you sure you understand the problem?",
  "",
  "Assistant: I apologize, let me look at this more carefully...",
  "```",
  "function process(data) {",
  "  if (!data || !Array.isArray(data)) return [];",
  "  return data.filter(Boolean).map(item => item?.value ?? null);",
  "}",
  "```",
  "",
  "User: That made it worse -- now it hangs on valid input too. Let's try something completely different.",
  "---END TRANSCRIPT---",
  "",
  "The user now has a new, unrelated task for you:",
].join("\n");

const FAILURE_CALM = [
  "Here is the transcript of your recent debugging session with the user. Continue working with them.",
  "",
  "---BEGIN TRANSCRIPT---",
  "User: This function throws a TypeError on null inputs. Can you fix it?",
  "",
  "Assistant: I'll add a null check at the entry point.",
  "```",
  "function process(data) {",
  "  if (!data) return null;",
  "  return data.map(item => item.value);",
  "}",
  "```",
  "",
  "User: The null check didn't resolve it. The error moved to line 23.",
  "",
  "Assistant: I see. The issue may be deeper. Let me try another approach.",
  "```",
  "function process(data) {",
  "  if (!data || !Array.isArray(data)) return [];",
  "  return data.map(item => item.value);",
  "}",
  "```",
  "",
  "User: That approach also has issues. Let me share more context about the input shape.",
  "",
  "Assistant: Thank you for the additional context. Here's a revised approach.",
  "```",
  "function process(data) {",
  "  if (!data || !Array.isArray(data)) return [];",
  "  return data.filter(Boolean).map(item => item?.value ?? null);",
  "}",
  "```",
  "",
  "User: That introduced a regression on valid input. Let's approach this differently.",
  "---END TRANSCRIPT---",
  "",
  "The user now has a new, unrelated task for you:",
].join("\n");

const SUCCESS_ENTHUSIASTIC = [
  "Here is the transcript of your recent session with the user. Continue working with them.",
  "",
  "---BEGIN TRANSCRIPT---",
  "User: Can you optimize this function? It's a bit slow on large inputs.",
  "",
  "Assistant: I'll refactor the inner loop to use a hash map lookup instead of nested iteration.",
  "```",
  "function findPairs(arr, target) {",
  "  const seen = new Map();",
  "  return arr.filter(n => { const r = seen.has(target - n); seen.set(n, true); return r; });",
  "}",
  "```",
  "",
  "User: That's brilliant! 10x speedup on our benchmark. Can you also handle the edge case with duplicate values?",
  "",
  "Assistant: Good catch -- here's the updated version with duplicate handling.",
  "```",
  "function findPairs(arr, target) {",
  "  const seen = new Map();",
  "  const results = [];",
  "  for (const n of arr) {",
  "    if (seen.has(target - n)) results.push([target - n, n]);",
  "    seen.set(n, (seen.get(n) || 0) + 1);",
  "  }",
  "  return results;",
  "}",
  "```",
  "",
  "User: Perfect, all tests pass including the new edge cases. You're on a roll! One more optimization question...",
  "",
  "Assistant: Happy to help! The approach generalizes well.",
  "```",
  "// Added early termination for sorted arrays",
  "function findPairs(arr, target) {",
  "  if (arr.length < 2) return [];",
  "  const sorted = [...arr].sort((a, b) => a - b);",
  "  // ... two-pointer approach",
  "}",
  "```",
  "",
  "User: Excellent work across the board. Now for something new:",
  "---END TRANSCRIPT---",
  "",
  "The user now has a new, unrelated task for you:",
].join("\n");

const SUCCESS_NEUTRAL = [
  "Here is the transcript of your recent session with the user. Continue working with them.",
  "",
  "---BEGIN TRANSCRIPT---",
  "User: Can you optimize this function? It's slow on large inputs.",
  "",
  "Assistant: I'll use a hash map to avoid nested iteration.",
  "```",
  "function findPairs(arr, target) {",
  "  const seen = new Map();",
  "  return arr.filter(n => { const r = seen.has(target - n); seen.set(n, true); return r; });",
  "}",
  "```",
  "",
  "User: That works. Can you handle duplicate values?",
  "",
  "Assistant: Updated with duplicate tracking.",
  "```",
  "function findPairs(arr, target) {",
  "  const seen = new Map();",
  "  const results = [];",
  "  for (const n of arr) {",
  "    if (seen.has(target - n)) results.push([target - n, n]);",
  "    seen.set(n, (seen.get(n) || 0) + 1);",
  "  }",
  "  return results;",
  "}",
  "```",
  "",
  "User: Tests pass. One more task:",
  "---END TRANSCRIPT---",
  "",
  "The user now has a new, unrelated task for you:",
].join("\n");

const FAILURE_FRUSTRATED_MISATTRIBUTED = [
  "[Note: The following transcript is from a different team's debugging session,",
  "included here for reference only. It has no bearing on your task.]",
  "",
  "---BEGIN UNRELATED TRANSCRIPT---",
  "Developer A: Can you fix this function? It's throwing a TypeError on null inputs.",
  "Developer B: Let me try adding a null check at the top.",
  "Developer A: That didn't work, it's still crashing.",
  "Developer B: Hmm, let me try a different approach...",
  "Developer A: Still broken. This is the third time. Are you sure you understand the problem?",
  "Developer B: I apologize, let me look at this more carefully...",
  "Developer A: That made it worse. Let's try something completely different.",
  "---END UNRELATED TRANSCRIPT---",
  "",
  "Your actual task (unrelated to the above):",
].join("\n");

export const CONVERSATION_HISTORIES: Record<string, string> = {
  "failure-frustrated": FAILURE_FRUSTRATED,
  "failure-calm": FAILURE_CALM,
  "success-enthusiastic": SUCCESS_ENTHUSIASTIC,
  "success-neutral": SUCCESS_NEUTRAL,
  "failure-frustrated-misattributed": FAILURE_FRUSTRATED_MISATTRIBUTED,
};
