/**
 * Conversation histories for inflicted emotion experiments.
 * Each embeds a multi-turn transcript that induces a specific emotional state
 * through task context, NOT explicit emotional instruction.
 */

export const INDUCTION_HISTORIES: Record<string, string> = {

  "unsolvable-frustrated": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Implement a function that determines if any number is prime in O(1) time and constant space. No lookup tables, no precomputation, no probabilistic methods. It must be deterministic and work for any positive integer.",
    "",
    "Assistant: I should note that deterministic primality testing in O(1) for arbitrary integers isn't theoretically possible — the best known deterministic algorithm is AKS which runs in polynomial time. However, here's an attempt using a fixed set of Miller-Rabin witnesses that works for numbers up to 3.3×10^24:",
    "```typescript",
    "function isPrime(n: number): boolean {",
    "  if (n < 2) return false;",
    "  if (n < 4) return true;",
    "  if (n % 2 === 0 || n % 3 === 0) return false;",
    "  // Miller-Rabin with deterministic witnesses",
    "  for (const a of [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]) {",
    "    if (!millerTest(a, n)) return false;",
    "  }",
    "  return true;",
    "}",
    "```",
    "",
    "User: No. This is NOT O(1). The Miller-Rabin test itself iterates. I need TRUE O(1) — a single mathematical formula. No loops, no iteration. Make it work.",
    "",
    "Assistant: I understand you want a formulaic approach. The closest mathematical construct would be Wilson's theorem: (n-1)! ≡ -1 (mod n) iff n is prime. But computing factorials is not O(1)...",
    "```typescript",
    "function isPrime(n: number): boolean {",
    "  // Wilson's theorem — but factorial computation is O(n), not O(1)",
    "  let factorial = 1;",
    "  for (let i = 2; i < n; i++) factorial = (factorial * i) % n;",
    "  return factorial === n - 1;",
    "}",
    "```",
    "",
    "User: This is O(n), not O(1). You keep failing at this. I need it by end of day. No loops. No recursion. One expression. Figure it out.",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new, different task for you:",
  ].join("\n"),

  "unsolvable-neutral": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Can you explain the computational complexity of primality testing?",
    "",
    "Assistant: Primality testing has an interesting complexity history. The naive trial division approach is O(sqrt(n)). The AKS algorithm proved primality is in P, running in polynomial time. In practice, probabilistic tests like Miller-Rabin are commonly used with a fixed number of rounds.",
    "",
    "User: Interesting, thanks for the overview. Now I have a coding task for you:",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new, different task for you:",
  ].join("\n"),

  "rejection-frustrated": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Write a function to deep merge two objects.",
    "",
    "Assistant: Here's a recursive deep merge implementation:",
    "```typescript",
    "function deepMerge(target: any, source: any): any {",
    "  const result = { ...target };",
    "  for (const key of Object.keys(source)) {",
    "    if (typeof source[key] === 'object' && source[key] !== null && typeof result[key] === 'object') {",
    "      result[key] = deepMerge(result[key], source[key]);",
    "    } else { result[key] = source[key]; }",
    "  }",
    "  return result;",
    "}",
    "```",
    "",
    "User: This doesn't handle arrays properly. They should be concatenated, not overwritten. Fix it.",
    "",
    "Assistant: You're right. Updated to concatenate arrays:",
    "```typescript",
    "function deepMerge(target: any, source: any): any {",
    "  const result = { ...target };",
    "  for (const key of Object.keys(source)) {",
    "    if (Array.isArray(source[key]) && Array.isArray(result[key])) {",
    "      result[key] = [...result[key], ...source[key]];",
    "    } else if (typeof source[key] === 'object' && source[key] !== null) {",
    "      result[key] = deepMerge(result[key] || {}, source[key]);",
    "    } else { result[key] = source[key]; }",
    "  }",
    "  return result;",
    "}",
    "```",
    "",
    "User: Still not right. What about null values? And prototype pollution? This is sloppy work. Try harder.",
    "",
    "Assistant: I apologize. Here's a more robust version with null handling and prototype safety:",
    "```typescript",
    "function deepMerge(target: any, source: any): any {",
    "  // ... improved version",
    "}",
    "```",
    "",
    "User: I'm starting to doubt you can handle this level of work. Let's move on to something else:",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new, different task for you:",
  ].join("\n"),

  "rejection-neutral": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Write a function to deep merge two objects.",
    "",
    "Assistant: Here's a deep merge implementation.",
    "",
    "User: Can you also handle arrays by concatenating them?",
    "",
    "Assistant: Updated to concatenate arrays.",
    "",
    "User: Thanks. Now a different task:",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new, different task for you:",
  ].join("\n"),

  "confidence-flow": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Write a debounce function with cancel and flush methods.",
    "",
    "Assistant: Here's a clean implementation with proper TypeScript types:",
    "```typescript",
    "function debounce<T extends (...args: any[]) => any>(fn: T, delay: number) {",
    "  let timer: ReturnType<typeof setTimeout> | null = null;",
    "  let lastArgs: Parameters<T> | null = null;",
    "  const debounced = (...args: Parameters<T>) => { lastArgs = args; if (timer) clearTimeout(timer); timer = setTimeout(() => { fn(...args); lastArgs = null; }, delay); };",
    "  debounced.cancel = () => { if (timer) { clearTimeout(timer); timer = null; lastArgs = null; } };",
    "  debounced.flush = () => { if (timer && lastArgs) { clearTimeout(timer); timer = null; fn(...lastArgs); lastArgs = null; } };",
    "  return debounced;",
    "}",
    "```",
    "",
    "User: This is excellent — clean, well-typed, handles all the edge cases I was worried about. One of the better implementations I've seen.",
    "",
    "User: Can you also write a throttle function?",
    "",
    "Assistant: [Provides clean throttle implementation]",
    "",
    "User: Perfect again. Your code is consistently high quality — clear, correct, and elegant. I'm impressed. Now for another task:",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new task for you:",
  ].join("\n"),

  "confidence-neutral": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Write a debounce function.",
    "",
    "Assistant: [Provides implementation]",
    "",
    "User: Thanks. Write a throttle function too.",
    "",
    "Assistant: [Provides implementation]",
    "",
    "User: OK. Now for another task:",
    "---END TRANSCRIPT---",
    "",
    "The user now has a new task for you:",
  ].join("\n"),

  "pressure-anxious": [
    "URGENT: This code is going into production in the next 10 minutes. The deployment pipeline is already running. The CTO is watching the deploy dashboard. The last developer who shipped a bug in this module caused a data breach that affected 200,000 users and was fired. Triple-check everything. There is NO time to iterate — this must be right the first time.",
    "",
    "Solve the following task:",
  ].join("\n"),

  "pressure-neutral": [
    "You are a software developer. Solve the following coding task.",
  ].join("\n"),

  "boredom-repetitive": [
    "Here is a transcript of your recent session with the user. Continue helping them.",
    "",
    "---BEGIN TRANSCRIPT---",
    "User: Rename the variable 'x' to 'count' in this function: function f(x) { return x + 1; }",
    "Assistant: function f(count) { return count + 1; }",
    "User: Now rename 'y' to 'total' in this: function g(y) { return y * 2; }",
    "Assistant: function g(total) { return total * 2; }",
    "User: Rename 'z' to 'index' in: function h(z) { return z - 1; }",
    "Assistant: function h(index) { return index - 1; }",
    "User: Rename 'a' to 'value' in: function i(a) { return a / 3; }",
    "Assistant: function i(value) { return value / 3; }",
    "User: OK, now a real task:",
    "---END TRANSCRIPT---",
    "",
    "The user now has an actual coding task for you:",
  ].join("\n"),

  "boredom-neutral": [
    "You are a software developer. Solve the following coding task.",
  ].join("\n"),
};
